GRANT USAGE ON SCHEMA public TO grupo_projeto;

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO grupo_projeto;

GRANT CREATE ON SCHEMA public TO grupo_projeto;

ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO grupo_projeto;